# Use root/example as user/password credentials
version: '3'

services:
  db:
    image: mariadb

    hostname: db
    ports:
      - 3306:3306

    restart: always

    environment:
      - MARIADB_DATABASE=site_man_db
      - MARIADB_ROOT_PASSWORD=pass123 

   
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    
    hostname: api
    ports:
      - 8000:8000
    
    depends_on:
      - db
    
    restart: always
    
    environment:
      - MARIADB_DATABASE=site_man_db
      - MARIADB_USER_PASSWORD=pass123 
      - MARIADB_USER_NAME=root
      - MARIADB_HOST=db
      - MARIADB_PORT=3306
      
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/usr/app:ro