# Use root/example as user/password credentials
version: '3'

services:
  db:
    image: mariadb
    hostname: db
    restart: always
    ports:
      - 3306:3306
    
    environment:
      MARIADB_DATABASE: site_man_db
      MARIADB_ROOT_PASSWORD: pass123 
    
  api:
    hostname: api
    build: 
      context: .
      dockerfile: Dockerfile
    
    restart: always
    ports:
      - 8000:8000