version: '3'


volumes:
  db-volume:

services:
  mariadb:
    image: mariadb

    hostname: mariadb
    ports:
      - 3306:3306

    restart: always

    environment:
      - MARIADB_DATABASE=keycloak
      - MARIADB_ROOT_PASSWORD=root 
      - MARIADB_USER=kc_dev
      - MARIADB_PASSWORD=kc_pass 

    volumes:
      - db-volume:/var/lib/mysql/

  keycloak:
    build: 
      context: .
    
    command: "start-dev --spi-connections-jpa-legacy-initialize-empty=true"

    environment:
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_FEATURES: declarative-user-profile
      DB_VENDOR: mariadb
      # DB_ADDR: db
      # DB_PORT: 3306

      # KC_DB_SCHEMA: keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: mariadb
      KC_DB_URL_PORT: 3306
      KC_DB_USERNAME: kc_dev
      KC_DB_PASSWORD: kc_pass
      KEYCLOAK_ADMIN: kc_admin
      KEYCLOAK_ADMIN_PASSWORD: kc_admin_pass

    ports:
      - '8443:8443'
      - '8080:8080'
    depends_on:
      - mariadb
    restart: always

