name: Intrusion Management API testing

on:
  push:
    paths:
      - intrusion-management-api/**
      - '!**.md'
      - '!**.pdf'
      - '!**.docx'
      - '!**.gitignore'
      - '!**.txt'
  pull_request:
    paths:
      - intrusion-management-api/**
      - '!**.md'
      - '!**.pdf'
      - '!**.docx'
      - '!**.gitignore'
      - '!**.txt'
jobs:
  run_tests:
    name: Run Intrusion Management API tests
    runs-on: ubuntu-latest

    env:
      RABBIT_MQ_USERNAME: myuser
      RABBIT_MQ_PASSWORD: mypassword
      RABBIT_MQ_URL: localhost:5672
      RABBIT_MQ_EXCHANGE_NAME: request-video-exchange
      RABBIT_MQ_QUEUE_NAME: request-video-queue

    services:
      rabbitmq:
        image: rabbitmq:3.8-management-alpine
        env:
          RABBIT_MQ_USERNAME: myuser
          RABBIT_MQ_PASSWORD: mypassword
          RABBIT_MQ_URL: localhost:5672
          RABBIT_MQ_EXCHANGE_NAME: request-video-exchange
          RABBIT_MQ_QUEUE_NAME: request-video-queue
        ports:
          - 5672:5672

    container: python:3.10-alpine

    defaults:
      run:
        working-directory: ./intrusion-management-api
    steps:
    - uses: getong/rabbitmq-action@v1.2
      with:
        rabbitmq version: '3.8.2-management-alpine'
        host port: 5672
        RABBIT_MQ_USERNAME: myuser
        RABBIT_MQ_PASSWORD: mypassword
        RABBIT_MQ_URL: localhost:5672
        RABBIT_MQ_EXCHANGE_NAME: request-video-exchange
        RABBIT_MQ_QUEUE_NAME: request-video-queue
      - name: Pulling git repo
        uses: actions/checkout@v3
      - name: Install all dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          PYTHONPATH=${PYTHONPATH}:./src python -m pytest -vv