name: Intrusion Management API testing

on:
  push:
    paths:
      - intrusion-management-api/**
      - '!**.md'
      - '!**.pdf'
      - '!**.docx'
      - '!**.gitignore'
      - '!**.txt'
  pull_request:
    paths:
      - intrusion-management-api/**
      - '!**.md'
      - '!**.pdf'
      - '!**.docx'
      - '!**.gitignore'
      - '!**.txt'
jobs:
  run_tests:
    name: Run Intrusion Management API tests
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3.8-management-alpine
        env:
          RABBITMQ_DEFAULT_USER: myuser
          RABBITMQ_DEFAULT_PASS: mypassword
        ports:
          - 5672:5672

    container: python:3.10-alpine

    defaults:
      run:
        working-directory: ./intrusion-management-api
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v3
      - name: Install all dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          PYTHONPATH=${PYTHONPATH}:./src python -m pytest
        env:
          RABBITMQ_HOST: 127.0.0.1
          RABBITMQ_PORT: ${{ job.services.rabbitmq.ports['5672'] }}